language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIARHQZKHKSBUTZJG5M
  secret_access_key:
    secure: CXBquhcDZZ1Na2aWUcPrOQ7tXMNIMUsUo06uA8AR1NY0vJGpujfMvlEjvoKlKa13/s6S0nmjz1fzRIGRrD/fC4Guij8giUfzNqu4wyFpbY9UqvBL0+aafiF29ChweaOJOotZ8a5hatNkkZm9yg+PYFR8rBx8fxB+6lHtNzUy+nyPhj59LyT23qyNandKlw46J+nNzHO3Ix+9gdfvfmSFUqB5iNHt6DT2ssjQBxWW05U8vdtZygZGjaWGEj8abYo03B5arnqGlTiYpUGgwsdn3KqHitFYJ6SEq96hoCkQSaonkz0hxj48U1KhzM9vZe4mNOvCO732AIK/UBtbT4UIVmvgsaA2E+hya90V+TbWh5YbdqtUaLguBSjHzMae62BGAEOZB6Axjp0QC9ey3+2zoiu6X4I5y4LgwWc6jwHVGkAsbqj7btx7cFs9e2Zek0DUjeAAO1L/MTWpThuWv+lNLz8zGGr91TfiApU1+w32aAteomnx0tv3gNyqbS6msfqQz5nGhDqRqcvKqNEsVYSb6psQ/UdJ1SGR+lSuC2L2vxkN/bEXM3ElLMc6s8UDCuXv4+tGaV1o5QXBaLRWwaB25XBIMHLF23uzRyW+tEVYkWAYnIFJmxrxP6ATptA5vFY2XMEXc160nPIlAjyX7I9oXijFVJNROOeXh856u2AQdsw=
  bucket: adkison-experience
  skip_cleanup: true
  region: us-west-2
  acl: public_read
